version: "2"

services:
  app:
    build:
      context: .
    ports:
      - 3000
    depends_on:
      - redis
    environment:
      - APP_ENV=production
  fe:
    build:
      context: front-end
    ports:
      - 4000
    depends_on:
      - app
    environment:
      - APP_ENV=production
  nginx:
    build:
      context: nginx
    ports:
      - 80:80
    depends_on:
      - app
  redis:
    image: redis:latest
    ports:
      - 6380:6379 # comment out redis "ports" in production (you don't want to expose redis)
